pipeline {
    agent any
    
    parameters {
        string(
            name: 'path_GitHub', 
            defaultValue: 'C:\\Users\\ASYost\\source\\repos\\ra-cicd-test-old\\', 
            description: 'Enter the path to your CICD GitHub repository.'
            )
        string(
            name: 'acdFileName', 
            defaultValue: '', 
            description: 'Enter the file name of the ACD project under development')
    }

    stages {
        stage ('Build') {
            steps {
                echo 'Starting Build...'
                //bat 'whoami'
                // script {
                //     sh 'ls -d */'
                // }

                bat """
                    cd C:\\Users\\ASYost\\source\\repos\\ra-cicd-test-old\\cicd-config\\stage-test\\stage-test-configuration\\LogixSDKDemoApp
                    dotnet build
                """

                // script {
                //     def exitCode_1 = bat(returnStatus: true, script: 'dotnet build')
                //     if (exitCode_1 == 0) {
                //         echo 'Executable ran successfully'
                //     } else {
                //         error 'Executable failed to run'
                //     }
                // }
                
            }
        }
        stage('Test') {
            steps {
                echo 'Starting Test..'
                // bat """
                //     C:\\Users\\ASYost\\source\\repos\\ra-cicd-test-old\\cicd-config\\stage-test\\stage-test-configuration\\LogixSDKDemoApp\\bin\\Debug\\net6.0\\TestStage_CICDExample.exe C:\\Users\\ASYost\\source\\repos\\ra-cicd-test-old\\ CICD_test.ACD
                // """
                bat "${params.path_GitHub}cicd-config\\stage-test\\stage-test-configuration\\LogixSDKDemoApp\\bin\\Debug\\net6.0\\TestStage_CICDExample.exe ${params.path_GitHub} ${params.acdFileName}"
                // "${env.WORKSPACE}/JenkinsScripts/myScript.groovy"

                // script {
                //     def exitCode_2 = bat(returnStatus: true, script: 'cicd-config/stage-test/stage-test-configuration/LogixSDKDemoApp/bin/Debug/net6.0/TestStage_CICDExample.exe')
                //     if (exitCode_2 == 0) {
                //         echo 'Executable ran successfully'
                //     } else {
                //         error 'Executable failed to run'
                //     }
                // }
            }
        }
        stage('Publish') {
            steps {
                echo 'Starting Publishing..'
            }
        }

        stage('Deliver') {
            steps {
                echo 'Starting Delivery....'
            }
        }
    }
}
