pipeline {
    agent any
    
    environment {
        PATH_GITHUB = 'C:\\Users\\ASYost\\source\\repos\\ra-cicd-test-old\\'
        ACDFILENAME = 'CICD_test.ACD'
        GITHUB_USER_EMAIL = 'andresyost2000@gmail.com'
        GITHUB_USER_NAME = 'Andre Sandor Yost'
        GITHUB_USERNAME = 'rockwell-user'
        GITHUB_PASSWORD = 'RockwellGithub!'
        GITHUB_ACCESTOKEN = 'ghp_mpOj91xiccmZmGnGezvyxYLNWNas8Z39k?z?E?P?'
        //GITHUB_ACCESTOKEN = credential('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')
        GITHUB_REPO_NAME = 'ra-cicd-test-old'
        GITHUB_DEV_BRANCH = 'dev-branch'
        DOTNET_VERSION = '8'
        DOTNET_INSTALL_DIR = 'C:\\Program Files\\dotnet'
        TEST_RESULT = ''
    }

    stages {
        stage('Check .NET SDK') {
            steps {
                echo 'Starting .NET SDK Check....'
                //bat 'cd %PATH_GITHUB%'
                script {
                    def dotnetVersionInstalled = bat(
                        script: 'dotnet --version',
                        returnStdout: true
                    ).trim()
                    echo "${dotnetVersionInstalled}"
                    echo "${env.DOTNET_VERSION}"
                    echo "${dotnetVersionInstalled.startsWith(env.DOTNET_VERSION)}"
                    echo "${params.dotnetVersionInstalled.substring(0,1)}"
                    echo "${params.dotnetVersionInstalled.substring(0,2)}"
                    echo "${params.dotnetVersionInstalled.substring(0,3)}"
                    echo "${params.dotnetVersionInstalled.substring(0,4)}"
                    echo "${params.dotnetVersionInstalled.substring(0,1) == '8'}"
                    if (!dotnetVersionInstalled.startsWith(env.DOTNET_VERSION)) {
                        echo "Installing .NET SDK $DOTNET_VERSION..."
                        // Download and install .NET SDK 6.0 using curl
                        bat label: 'Install .NET SDK 8.0',
                            script: """
                                mkdir "$DOTNET_INSTALL_DIR"
                                cd "$DOTNET_INSTALL_DIR"
                                curl -o dotnet-install.ps1 -L https://dot.net/v1/dotnet-install.ps1
                                powershell -ExecutionPolicy Bypass -File .\\dotnet-install.ps1 -Channel 8.0 -InstallDir \"$DOTNET_INSTALL_DIR\" -NoPath
                            """
                    } else {
                        echo ".NET SDK $DOTNET_VERSION is already installed."
                    }
                }
            }
        }
        stage ('Build') {
            steps {
                echo 'Starting Build....'

                bat """
                    cd %PATH_GITHUB%cicd-config\\stage-test\\stage-test-configuration\\LogixSDKDemoApp
                    dotnet build
                """
                
            }
        }
        stage('Test') {
            steps {
                echo 'Starting Test....'

                script {
                    testResult = bat(script: "@%PATH_GITHUB%cicd-config\\stage-test\\stage-test-configuration\\LogixSDKDemoApp\\bin\\Debug\\net6.0\\TestStage_CICDExample.exe %PATH_GITHUB% %ACDFILENAME%", returnStdout: true).trim()
                    echo testResult
                    displayContentsOfMostRecentTextFile("${env.PATH_GITHUB}cicd-config\\stage-test\\test-reports")
                    
                    TEST_RESULT = testResult
                    // if (testResult == 'SUCCESS') {
                    //     sendEmail('SUCCESS')
                    // } else if (testResult == 'FAILURE') {
                    //     sendEmail('FAILURE')
                    // } else {
                    //     echo "Unknown output: $testResult"
                    // }
                }
            }
        }
        stage('Release') {
            steps {
                script {
                    if (TEST_RESULT == 'SUCCESS') {
                        echo 'Test SUCCESS: Starting to release development results....'
                        def cleaned_token = env.GITHUB_ACCESTOKEN.replaceAll("\\?", "")
                        def gitUrl = "https://${env.GITHUB_USERNAME}:${cleaned_token}@github.com/${env.GITHUB_USERNAME}/${env.GITHUB_REPO_NAME}.git"
                        bat """
                            cd %PATH_GITHUB%
                            git config --global --add safe.directory "*"
                            git config --global core.autocrlf false
                            git remote set-url origin ${gitUrl}
                            git config --global user.email %GITHUB_USER_EMAIL%
                            git config --global user.name "%GITHUB_USER_NAME%"
                            git branch -a
                            git checkout %GITHUB_DEV_BRANCH%
                            git add -A
                            git commit -m "test"
                            git push origin %GITHUB_DEV_BRANCH%
                        """
                    }
                    else {
                        echo 'Test FAILURE: Return to Studio 5000 Logix Designer, correct the error, and push a new commit.'
                    }
                }
                
            }
        }
        stage('Deploy') {
            steps {
                echo 'Starting Deployment....'
            }
        }
    }
    post {
        always {
            echo 'Cleaning up workspace...'
            deleteDir() /* clean up our workspace */
        }
        success {
            echo 'This CI/CD pipeline executed successfully!'
        }
        failure {
            echo 'This CI/CD pipeline failed with errors.'
        }
    }
}


def sendEmail(status) {
    emailext(
        body: "The C# script for the CI/CD test stage was a ${status}.",
        subject: "CI/CD Test Stage Result: ${status}",
        to: 'andresyost2000@gmail.com'
        )
}

def displayContentsOfMostRecentTextFile(folderPath) {
    def fileList = bat(script: "dir /b /o:-d ${folderPath}", returnStdout: true).trim().split('\r\n')
    if (fileList.size() > 0) {
        def mostRecentFile = fileList[1]
        echo "The contents of the most recent test file (${mostRecentFile}):"
        def fileContents = readFile("${folderPath}\\${mostRecentFile}")
        echo "${fileContents}"
    } else {
        echo "No text files found in the folder: ${folderPath}"
    }
}